// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/dogs.tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/InstagramEmbeded.tsx";
import * as $$2 from "./islands/InstagramIsland.tsx";
import * as $$3 from "./islands/Navbar.tsx";
import * as $$4 from "./islands/SearchBox.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/dogs.tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/InstagramEmbeded.tsx": $$1,
    "./islands/InstagramIsland.tsx": $$2,
    "./islands/Navbar.tsx": $$3,
    "./islands/SearchBox.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
